services:
  postgresql:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ggwp
    ports:
      - "5439:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
